events {}

http {
    server {
        listen 80;

        # Transactions microservice
        location /api/transactions {
            proxy_pass http://transactions:4000/transactions;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Banking backend
        location /banking/ {
            proxy_pass http://backend:5090/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Frontend - everything else
        location / {
            proxy_pass http://frontend:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}